sudo: required

services:
  - docker

before_install:
  - docker image build -t 17042010/docker-react -f Dockerfile.Dev .

script:
  - docker container run -e -CI=true 17042010/docker-react npm run test